### PR TITLE
Fix failing test and add support for Python 3.7

### PR DESCRIPTION
**Pull request by somexpert**

### CODE REVIEW

**Comment by somexpert** [comment]
ping @ldko, @madhulika95b, this is ready for review. The redirect test started failing a while ago, but I don't know why. It had been expecting a 301 Moved Permanently status code and that worked until it didn't. Now it gets a 308 Permanent Redirect status code, which is still a redirect code. But no commits were made and all our requirements are fully nailed down, so I really don't know what made the test start failing. But anyways, I just updated the expected value and then went ahead and also added test envs for Python 3.7 and updated the docs to show that it works on that version too.

**Review by madhuBayy — APPROVED** [review]
Looks fine :+1:

**Review by ldko — APPROVED** [review]
Maybe a dependency of a pinned requirement was changed? Looks fine to me :+1:

**Comment by somexpert** [comment]
@ldko, that's certainly possible. In any case, these pass now so I'm gonna stop thinking about it :smile: 
...until they break again

**Pull request merged**
